### ISSUE TITLE
 Race category OTH and ASKU are not  Outputting as "NULL" 

### ISSUE THREAD

**Issue by mmatiasalt** [drajer-health/eCRNow#648] opened 2024-02-01 17:16 UTC
Subticket of https://github.com/drajer-health/eCRNow/issues/620: AthenaPractice v3.1.2
Issue stated as resolved in 3.1.2, but reports received that Race category OTH and ASKU are not outputting as NULL. 

Adding sample files of Race Category OTH and ASKU queries
https://github.com/drajer-health/eCRNow/files/13968530/Race_OTH_and_ASKU_Loadingquery.zip

**Comment by ctobias84** [comment] 2024-02-02 01:19
Yes this issue is still occurring in both ECRnow v2 and v3.1.2.

**Comment by ctobias84** [comment] 2024-02-02 16:52
[Race_OTH_and_ASKU_Loadingquery.zip](https://github.com/drajer-health/eCRNow/files/14142949/Race_OTH_and_ASKU_Loadingquery.zip)

**Comment by AGABB** [comment] 2024-02-06 20:46
Hi @ctobias84 - Just to confirm, are the files that you shared generated from v2 or v3.1.2?

**Comment by ctobias84** [comment] 2024-02-07 01:11
the sample files we provided were created with v2 of ECRnow.

**Comment by AGABB** [comment] 2024-02-07 12:07
@ctobias84 Thank you. A fix for the issue of OTH and ASKU not getting converted to NF was added to v3:

![image](https://github.com/drajer-health/eCRNow/assets/107709349/3379587b-201b-44cf-a73e-bd18e86ee0f2)
![image](https://github.com/drajer-health/eCRNow/assets/107709349/3e49886f-73f5-4fcf-b6c6-107a15494af3)

Note that the same !isCodingNullFlavor(race)) check does not exist in v2

<img width="320" alt="image" src="https://github.com/drajer-health/eCRNow/assets/107709349/e7b2c40b-f9a5-41b9-a192-45d77a4d2f6a">

Above you stated that this issue was occurring in in both ECRnow v2 and v3.1.2. If you are still seeing it occur in 3.1.2, something is not working as intended. If this is the case, can you please sent the same files as above but created with the 3.1.2 version for inspection?

**Comment by nbashyam** [comment] 2024-03-27 20:09
we are not modifying 2.X of the app, the issue is already resolved in 3.X.

**Closed** 2024-04-09 13:46 UTC
