### ISSUE TITLE
Filter Problems if it belongs to an encounter which not in the current context

### ISSUE THREAD

**Issue by markmaltbyoracle** [drajer-health/eCRNow#671] opened 2024-02-23 01:49 UTC

**Comment by bhuvansalanke** [comment] 2024-02-23 16:54
The Problem is added with a Encounter reference in the condition resource.
If the encounter reference is not equal to the current context, such Problems needs to be filtered.
The FHIR server today returns all the Problem without accounting for the encounter if passed. It only accounts for diagnosis.

**Comment by nbashyam** [comment] 2024-02-26 17:17
Bhuvan - Which baseline is this in ? In 3.X baseline this is controlled by the custom-queries and is not controlled by the app.

**Comment by nbashyam** [comment] 2024-03-27 20:06
This is already addressed in 2.X and 3.X.
In 3.X - custom queries can be used to execute this.

**Comment by nbashyam** [comment] 2024-04-10 14:26
Already part of the baseline.

Refere to R4ResourcesData.java for 2.X 
For 3.X refer to CustomQueryConfiguration.md

**Closed by nbashyam** 2024-04-10 14:26 UTC
